<?php
//------------ Menu -----------------
@define ('_xindungspamwebsitechungtoi','Please do not spam our website!');
@define ('_visaochochungtoi','Why choose My Nhu services');
@define ('_daily','Agency');
@define ('_timkiem','Search');
@define ('_congtytuvanbds','Real estate consulting company');
@define ('_tourkhuyenmai','<strong>Tour </strong> promotion');
@define ('_tinvavideo','<strong>News &amp; video </strong> jaya travel');
@define ('_dattour','Book tour');
@define ('_xacnhan','Confirm');

@define ('_tatca','All');
@define ('_khunghiduong','Khu nghỉ dưỡng');
@define ('_sangold','Golf course');
@define ('_vanchuyen','Transport');
@define ('_tournoibat','Highlights tour');
@define ('_khoihanh','Departure');
@define ('_giatour','Price');
@define ('_gtnu','Female');
@define ('_gtnam','Male');
@define ('_vietnam','VietNam');
@define ('_nuocngoai','Foreigner');
@define ('_embe','Baby');
@define ('_emnho','Kid');
@define ('_sosinh','New born');
@define ('_khong','No');
@define ('_co','Yes');
@define ('_danhsachkhachhang','Customer info list');
@define ('_loaikhach','Type');
@define ('_dotuoi','Age');
@define ('_phongdon','Single room');
@define ('_visa','Visa');
@define ('_thoigian','Time');
@define ('_socho','Seats');
@define ('_xemtatcacatour','View all other tours');
@define ('_tuvanvadatcho','Consult &amp; booking');
@define ('_diachivanphong','Address');
@define ('_tour','Tour');
@define ('_qahuongdan','(Q&amp;A) User Guide');
@define ('_coffeeandfood','Coffee &amp; food menu');
@define ('_parkmap','Park map');
@define ('_denvoichungtoi','Connect us');
@define ('_email','Email');
@define ('_tieude','Subject');
@define ('_theodoichungtoi','Follow us');
@define ('_noidungguidentabico','Note send to TABICO');
@define ('_tamnhinsumenh','Vision &amp; mission');
@define ('_bancantuvan','Do you need advice?');
@define ('_tailieu','Document');
@define ('_lienketnhanh','Link');
@define ('_hosonangluc','Capacity profile');
@define ('_hotrokhachhang','Support');
@define ('_ketnoichungtoi','Connect with us');
@define ('_gioithieuvecongty','About us');
@define ('_hethongcuahang','Shop system');
@define ('_quychequanlyhoatdong','Regulation of operational management');
@define ('_albumanh','Album');
@define ('_cuahang','Store');
@define ('_huongdandatmon','Order guide');
@define ('_hinhanhtaimucdong','Muc Dong images');
@define ('_xemthemhinhanh','View more');
@define ('_hethongbanhmi','Muc Dong system');
@define ('_giomocua','Giờ mở cửa');
@define ('_thucdon','Menu');
@define ('_chuyencua','Story of');
@define ('_thongtinkhuyenmai','Promotion news');
@define ('_dichvucuachungtoi','Our services');
@define ('_formlienhe','Contact Form');
@define ('_htthanhtoan', 'Form of payment');
@define ('_ngaydang','Post');
@define ('_duocpham','Medicine');
@define ('_duocmypham','Cosmeceuticals');
@define ('_thietbiyte','Medical equipment');
@define ('_muangay','Add to cart');
@define ('_dangkytuvan','Sign up for advice');
@define ('_chondanhmuc','Select one');
@define ('_banchuadangnhap','Please login to access this page!');
@define ('_vechungtoi','About us');
@define ('_cackhoahoc','Courses');
@define ('_lichhoc','Schedule');
@define ('_anhvideo','Picture - video');
@define ('_doinetve','Something about us');
@define ('_hoatdongcuachungtoi','Our activities');
@define ('_hocviennoigi','What students say');

@define ('_lienhevoichungtoi','Contact with us');
@define ('_ykienkhachhang','Customer reviews');
@define ('_goidebaogia','Call for a quote');
@define ('_loaiphong','Room Type');
@define ('_lapdat','Installation');
@define ('_laybaogiatufanpage','Get quotes from fanpage');
@define ('_muahangnhanhlapdattoanquoc','Buy fast, install nationwide');
@define ('_ngonngu','Language');
@define ('_mangxahoi','Social network');
@define ('_hotlinetuvan','Hotline');
@define ('_datphongngay','Book now');
@define ('_giachitu','price from');
@define ('_nguoilon','Adult');
@define ('_treem','child');
@define ('_thongtin','Information');
@define ('_gioithieuve','About');
@define ('_tienichcaocap','High-end gadgets');
@define ('_ngayalert','The travel date must be greater than or equal to the arrival date Current date ');
@define ('_hoatdong','Work');
@define ('_hon30nam','Over 30 years');
@define ('_tienich','Utilities');
@define ('_tuvanngay','Advice');
@define ('_motsohinhanh','Some photos of our hotel');
@define ('_dapungdaydu','Our hotel offers full service, most advanced facilities');
@define ('_album','Album');
@define ('_moidem','per day');
@define ('_cacloaiphong','Rooms Type');
@define ('_baomatthongtin','Fill out the information to get the desired room, all information is confidential');
@define ('_formdatphong','Booking Form');
@define ('_datphong','Booking');
@define ('_nhahang','Restaurant');
@define ('_trangchu','Home');
@define ('_gioithieu','About us');
@define ('_sanpham','Products');
@define ('_tintuc','News');
@define ('_tuyensinh','Tuyển sinh');
@define ('_sukien','Event');
@define ('_gocnhanong','Farm corner');
@define ('_dichvu','Services');
@define ('_chinhsach','Policies');
@define ('_congtrinh','work');
@define ('_duan','projects');
@define ('_tuyendung','Recruitment');
@define ('_khuyenmai','Offer');
@define ('_khohang','Warehouse');
@define ('_thuvien','Libraries');
@define ('_lienhe', 'Contact');
@define ('_quangcao', 'Advertisement');
@define ('_doitac','Partner');
@define ('_banggia','Price list');
@define ('_linhvucdautu','Investment sector');
@define ('_quanhecodong','Investor relations');
@define ('_nhaptukhoatimkiem', 'Enter search keyword');
@define ('_chuanhaptukhoa','You did not enter search keywords');
@define ('_ketquatimkiem', 'Search Results');
@define ('_quytrinhsanxuat','Production process');
@define ('_chinhsachquydinh','Policy - regulation');
// ------------ Danh mục + Nỗi bật----------------- 
@define ('_danhmucsanpham','Product Categories');
@define ('_danhmucdichvu','Service list');
@define ('_sanphamtieubieu','Special Products');
@define ('_sanphamnoibat','Hot Products');
@define ('_sanphambanchay','Bestsellers');
@define ('_sanphammoi','New Products');
@define ('_duantieubieu','Typical projects');
@define ('_duannoibat','Project highlights');
@define ('_congtrinhtieubieu','Typical');
@define ('_congtrinhnoibat','Work highlights');
@define ('_congtrinhdangthuchien','Work is done');
@define ('_congtrinhdathuchien','Work was done');
@define ('_tintucvasukien','News and Events');
@define ('_tintucsukien','News - Events');
@define ('_tintucnoibat', 'News Highlights');
@define ('_tintucmoi', 'News');
@define ('_congtrinhmoi', 'New work');
@define ('_duanmoi', 'New Project');
@define ('_hotlinedathang','Hotline');
@define ('_bandoduongdi','Road map');
// ---------------- Tiêu đề ----------------
@define ('_hotrotructuyen','Online Support');
@define ('_thongketruycap','Access statistics');
@define ('_dangonline','Online');
@define ('_daonline','Has online');
@define ('_ngayhomnay','Today');
@define ('_ngayhomqua','Yesterday');
@define ('_thongketuan','Statistics week');
@define ('_thongkethang','Months');
@define ('_tongtruycap', 'Total Access');
@define ('_tong','Total');

//---------------- Tiện ích ----------------
@define ('_tienich','Utilities');
@define ('_giavang','Gold Update');
@define ('_ngoaite','Exchange rate');
@define ('_chungkhoan','Stock Information');
@define ('_thoitiet','Weather forecast');

// ----------------  Đăng ký nhận mail----------------
@define ('_nhapemailcuaban', 'Enter your email');
@define ('_emaildadangky', 'This email was registered before do.Cam you');
@define ('_guiemailthanhcong', 'Email subscribe successfully');
@define ('_guiemailthatbai', 'Sign up for emails failed. Please register again. Thank you');
@define ('_dangkynhantin', 'Subcribe');
@define ('_mailtit','Sign up now to receive promotions');
@define ('_maildesc','Sign up for our newsletter to receive notifications');
@define ('_guilienhethanhcong', 'Contact information has been submitted. <br /> Thank you');
@define ('_guilienhethatbai', 'Contact information not be sent. Please return later. <br /> Thank you');

//---------------- Gio hàng + Thanh toán ----------------
@define ('_thongtingiohang','The Shopping Cart');
@define ('_dongia','Unit price');
@define ('_soluong','Number');
@define ('_thanhtien','Amount');
@define ('_tieptucmuahang','Continue Shopping');
@define ('_tongtien', 'Total Price');

@define ('_giohang','Cart');
@define ('_ten','Name');
@define ('_hinhanh','Photo ');
@define ('_soluong','Number of ');
@define ('_mausac', 'Color');
@define ('_mau', 'Color');
@define ('_size', 'Size');
@define ('_tonggia','Total price');
@define ('_xoa','Delete');
@define ('_muatiep','Buy continues');
@define ('_xoatatca','Clear all');
@define ('_capnhat','Update');
@define ('_thanhtoan','Payment');
@define ('_thongtinkhachhang','Customer Information');

@define ('_nhapsoluong','Enter amount');
@define ('_chonsize','Choose size');
@define ('_chonmau','Choose color');
@define ('_dathang','Order');
@define ('_themvaogio','Add to cart');
@define ('_sanphamthemvaogiohang','This product was added to your cart');
@define ('_datmuasanpham','Order products');
@define ('_chonhinhthucthanhtoan','Choose form of payment');
@define ('_tinhthanhpho','City');
@define ('_quanhuyen','Trousers');
@define ('_ghichu2','Note');
@define ('_xemgiohang','View Cart');
@define ('_chontinhthanhpho','Choose city');
@define ('_chonquanhuyen','Choose trousers');
@define ('_khongcosanphamtronggiohang','No products in cart');

@define ('_thongtinkhachhang', 'Customer Information');
@define ('_hinhthucthanhtoan', 'Form of payment');
@define ('_nhanhanggiaotien', 'Get money delivery');
@define ('_quathenganhang', 'Through bank card');
@define ('_tinh', 'Region');
@define ('_chontinh', 'Select City');
@define ('_quan', 'County');
@define ('_chonquan', 'Choose a Region');
@define ('_hoantatdathang', 'Complete Order');
@define ('_khongcosanphamtronggiohang', 'There are no items in your shopping cart');

@define ('_bandanhgia','You considered');
@define ('_danhgiaroi','You have already rated roi.Vui assessed after 24h.Cam heart Thanks');

//---------------- Đăng ký + Đăng nhập + Đổi mật khẩu ----------------
@define ('_DANGNHAP','LOGIN');
@define ('_dangnhap','Login');
@define ('_tenthanhvien','Member Name');
@define ('_matkhau','Password');
@define ('_dangky','Sign up');
@define ('_doimatkhau','Change password');
@define ('_dangxuat','Log out');
@define ('_xinchao','Hello');
@define ('_dangnhapdeduocvaophongchat','Sign in to chat room');

@define ('_tendangnhap','Username');
@define ('_nhaplaimatkhau','Enter the password');
@define ('_ngaysinh','Date of birth');
@define ('_gioitinh','Gender');
@define ('_dangkythanhvien','Register');
@define ('_ngay','Date');
@define ('_thang','Month');
@define ('_nam','Year');
@define ('_nam2','Men');
@define ('_nu','Women');

@define ('_matkhaucu','Old password');

@define ('_thongtindangky', 'Registration Information');
@define ('_khachhangdadangky,','Registered Customer');
@define ('_luachon', 'Choices');
@define ('_taotaikhoanmoi', 'Create new account');
@define ('_neubancotaikhoan', 'If you already have an account! Please sign in to use these functions as well as other incentives for the members of the website ...');

@define ('_nhaptendangnhap','Enter your username');
@define ('_tendangnhaptu6den30kitu','Username from 6 to 30 characters');
@define ('_tendangnhapkhongduocchuakhoangtrang','Username can not contain spaces');
@define ('_tendangnhapkhongduocchuakitudatbiethoactiengvietcodau','Username can not contain special characters or accented Vietnamese');
@define ('_matkhaukhongduocchuakhoangtrang','Passwords should not contain spaces');
@define ('_matkhautu6den30kitu','Password between 6 and 30 characters');
@define ('_matkhaunhaplaikhongdung','Re-enter the wrong password');
@define ('_nhapmatkhau','Enter the password');
@define ('_nhapnhaplaimatkhau','Enter the repassword');
@define ('_sodienthoaikhongdung','Phone number incorrect');
@define ('_nhapemail','Enter your email');
@define ('_thucuabandaduocguidi', 'Contact information has been submitted. <br /> Thank you');
@define ('_guimailbiloi','Faulty system, please move to another position');
@define ('_hethongloi','Faulty system, please move to another position');
@define ('_tendangnhapdatontai','Username available');
@define ('_dangkythanhcong','Sign Up Success');
@define ('_dangnhapthanhcong','Logged in successfully');
@define ('_matkhaukhongdung','Wrong password');
@define ('_taikhoanchuakichhoat','Account has not been activated');
@define ('_tendangnhapkhongtontai','Username does not exist');
@define ('_thongtindangnhap','Login Information');
@define ('_khachhangchuacotaikhoan','Customers do not have account');
@define ('_quenmatkhau','Forgot password');
@define ('_thaydoithongtin','Change information');
@define ('_dangxuatthanhcong','Logout successful');
@define ('_thongbao','Notification');
@define ('_bandadangnhap','You are logged. Please switch to another position');
@define ('_laymatkhau','Get password');
@define ('_thaydoithongtin','Change information');

@define ('_thongtinthanhvien','Member information');
@define ('_vuilongkiemtralaiemail','Please check your email, we have sent the information back to your account, if no please check spam. Thank you');
@define ('_thongtinkhongchinhxac','Incorrect information');
@define ('_matkhaukhongdung','Wrong password');
@define ('_capnhatthanhcong','Update successful');
@define ('_matkhaucukhongduocchuakhoangtrang','Old password can not contain spaces');
@define ('_matkhaucutu6den30kitu','Old password between 6 and 30 characters');
@define ('_nhapmatkhaumoi','Enter your new password');
@define ('_nhapnhaplaimatkhaumoi','Enter a new password');
@define ('_matkhaumoi','A new password');
@define ('_nhaplaimatkhaumoi','Enter a new password');

//---------------- Left ----------------);
@define ('_daonline','Visitors');
@define ('_lienketwebsite','Web links...');
@define ('_tintucmoi','Newsletters');
@define ('_bando','Map');
@define ('_timkiemsanpham','Product Search');
@define ('_nhaptukhoa','Enter keywords...');

@define ('_doitac','Partner');
@define ('_xemtatca','View all');
@define ('_tatcasanpham','All products');
@define ('_lienketweb','LINKS');
@define ('_lienketweb2','.. web links ..');
@define ('_thongketruycap','Accer Counter');


@define ('_gui','Send');
@define ('_nhaplai','Re-enter');
@define ('_bandoduongdi','Road map');
@define ('_danhmucdichvu','Categories Services');
@define ('_tienichwebsite','Website Utilities');
@define ('_dathang','Ppurchase');


//------------- Contact --------
@define ('_mabaove', 'Security Code');
@define ('_mabaovesai', 'wrong security code');
@define ('_doimakhac', 'Refresh');
@define ('_nhapmabaove', 'Enter the code for');
@define ('_emailkhonghople', 'Email is invalid');

@define ('_diachi','Address');
@define ('_dienthoai','Phone');
@define ('_hovaten','Full name');
@define ('_chude','Topics');
@define ('_noidung','Content');
@define ('_ghichu','You can contact us from this website by filling the contact information form below. We will contact you within the shortest time. Please thank.');
@define ('_nhaphoten','Please enter a name');
@define ('_nhapdiachi','Please enter a address');
@define ('_nhapsodienthoai','Please enter your phone number');
@define ('_khonghople','Phone number is invalid');
@define ('_emailkhonghople','Email is invalid');
@define ('_nhapchude','Please enter Topic');
@define ('_nhapnoidung','Please enter Content');

//---------------- chi tiết sản phẩm ----------------
@define ('_chitietsanpham','Product details');
@define ('_thongtinchitiet','Details');
@define ('_masp','Code');
@define ('_gia','Price');
@define ('_giakm', 'Sale price');
@define ('_giamoi', 'New price');
@define ('_giagoc', 'Original price');
@define ('_giathitruong', 'Market price');
@define ('_giakhuyenmai', 'Price Promotion');
@define ('_ketquatimkiem','Search Results');
@define ('_masanpham','Product Code');
@define ('_tensanpham','Product Name');
@define ('_dientich','Acreage');
@define ('_kichthuoc','Size');
@define ('_trongluong','Weight');
@define ('_chatlieu','Material');
@define ('_nhasanxuat','Manufacturer');
@define ('_luotxem','Views');
@define ('_noidungsanpham','Product Content');
@define ('_sanphamkhac','Other room');
@define ('_khac','Other');
@define ('_sanphamcungloai','A work together categories');
@define ('_chitiet','Details');

@define ('_thongtinsanpham', 'Product Information');
@define ('_thongtinlienhe','Contact information');
@define ('_thongsokythuat', 'Technical data');
@define ('_binhluan', 'Comments');
@define ('_thongtinthanhtoan', 'Billing Information');
@define ('_huongdanthanhtoan', 'How to pay');

@define ('_tinlienquan','Related News');
@define ('_cacbaikhac','Other Articles');

@define ('_dangchuyentrang','Are turning the page');
@define ('_clickvaodayneukhongmuondoilau','Click here if you do not want to wait that long');

@define ('_goidien', 'Call');
@define ('_nhantin', 'Messages');
@define ('_chiduong', 'Directions');
@define ('_chiase','Share');

@define ('_duonglinkkhongtontai','This link does not exist. Please switch to another position <a href="">Go home</a>. Thank you!');
@define ('_loi404','Error: 404');

//---------------- Bình luận ----------------
@define ('_xemchitiet','Read more');
@define ('_xemtatca','View all');
@define ('_xemtiep','Read more');
@define ('_xemthem','See more');
@define ('_thugon','Collapse');
@define ('_traloi','Reply');
@define ('_tu30den1000','Comments from 30 to 1000 characters');
@define ('_vuilongnhanguihoanthanh','Please click on submit and complete');
@define ('_delaithongtin','Please leave your information');
@define ('_guivahoantat','Send & completion');
@define ('_nhaptiengvietcodau','Invites you to discuss, please enter accented Vietnamese ...');
@define ('_binhluanthanhcong','Send comments to cong.Chung I will review soon nhat.Thanks!');
?>